version: '3'
services:
  appClient:
    build:
      context: ./client/client/cliente
      dockerfile: Dockerfile
    image: apiappclient
    container_name: appclient
    ports:
      - '8082:8082'
    links:
      - db
  appNotification:
    build:
      context: ./notification
      dockerfile: Dockerfile
    image: apiappnotification
    container_name: appnotification
    ports:
      - '8085:8085'
    links:
      - db
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    image: apidb
    container_name: db
    ports:
     - '3306:3306'
    environment:
          - MYSQL_ROOT_HOST=%
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_PASSWORD=root
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
